#ifndef _H_CDXCommons
#define _H_CDXCommons

#include "CDXConstants.h"
#include <string>
#include <unordered_map>
#include <utility>

enum class EnhancedStereoType : int
{
    UNSPECIFIED,
    NONE,
    ABSOLUTE,
    OR,
    AND
};

const int KCDXMLChemicalFontStyle = 96;
const int kCDXMLSizeMultiplier = 20;
const int kCDXMLStyleSizeIndex = 2;

#pragma pack(push, 1)

struct CDXTextStyle
{
    uint16_t offset;
    uint16_t font_index;
    uint16_t font_face;
    uint16_t font_size;
    uint16_t font_color;
};

struct CDXTextStyleProperty
{
    uint16_t tag;
    uint16_t size;
    uint16_t style_count;
    CDXTextStyle styles[];
};

#pragma pack(pop)

enum class ECDXType
{
    CDXString,
    CDXDate,
    CDXINT8,
    CDXINT16,
    CDXUINT8,
    CDXUINT16,
    CDXUINT32,
    CDXRepresentsProperty,
    CDXBooleanImplied,
    CDXBoolean,
    CDXObjectID,
    CDXFontTable,
    CDXPoint2D,
    CDXPoint3D,
    CDXINT32,
    CDXRectangle,
    CDXColorTable,
    CDXColorTableCDXINT16,
    CDXElementList,
    CDXFormula,
    CDXObjectIDArray,
    CDXObjectIDArrayWithCounts,
    CDXGenericList,
    CDXFLOAT64,
    CDXINT16ListWithCounts,
    CDXUnformatted,
    CDXCoordinate,
    CDXCurvePoints,
    CDXCurvePoints3D,
    CDXvaries
};

const std::unordered_map<std::string, int> kCDXProp_Bond_DisplayStrToID = {{"Solid", kCDXBondDisplay_Solid},
                                                                                      {"Dash", kCDXBondDisplay_Dash},
                                                                                      {"Hash", kCDXBondDisplay_Hash},
                                                                                      {"WedgedHashBegin", kCDXBondDisplay_WedgedHashBegin},
                                                                                      {"WedgedHashEnd", kCDXBondDisplay_WedgedHashEnd},
                                                                                      {"Bold", kCDXBondDisplay_Bold},
                                                                                      {"WedgeBegin", kCDXBondDisplay_WedgeBegin},
                                                                                      {"WedgeEnd", kCDXBondDisplay_WedgeEnd},
                                                                                      {"Wavy", kCDXBondDisplay_Wavy},
                                                                                      {"HollowWedgeBegin", kCDXBondDisplay_HollowWedgeBegin},
                                                                                      {"HollowWedgeEnd", kCDXBondDisplay_HollowWedgeEnd},
                                                                                      {"WavyWedgeBegin", kCDXBondDisplay_WavyWedgeBegin},
                                                                                      {"WavyWedgeEnd", kCDXBondDisplay_WavyWedgeEnd},
                                                                                      {"Dot", kCDXBondDisplay_Dot},
                                                                                      {"DashDot", kCDXBondDisplay_DashDot}};

const std::unordered_map<int, std::string> kCDXProp_Bond_DisplayIdToStr = {{kCDXBondDisplay_Solid, "Solid"},
                                                                                      {kCDXBondDisplay_Dash, "Dash"},
                                                                                      {kCDXBondDisplay_Hash, "Hash"},
                                                                                      {kCDXBondDisplay_WedgedHashBegin, "WedgedHashBegin"},
                                                                                      {kCDXBondDisplay_WedgedHashEnd, "WedgedHashEnd"},
                                                                                      {kCDXBondDisplay_Bold, "Bold"},
                                                                                      {kCDXBondDisplay_WedgeBegin, "WedgeBegin"},
                                                                                      {kCDXBondDisplay_WedgeEnd, "WedgeEnd"},
                                                                                      {kCDXBondDisplay_Wavy, "Wavy"},
                                                                                      {kCDXBondDisplay_HollowWedgeBegin, "HollowWedgeBegin"},
                                                                                      {kCDXBondDisplay_HollowWedgeEnd, "HollowWedgeEnd"},
                                                                                      {kCDXBondDisplay_WavyWedgeBegin, "WavyWedgeBegin"},
                                                                                      {kCDXBondDisplay_WavyWedgeEnd, "WavyWedgeEnd"},
                                                                                      {kCDXBondDisplay_Dot, "Dot"},
                                                                                      {kCDXBondDisplay_DashDot, "DashDot"}};

const std::unordered_map<std::string, EnhancedStereoType> kCDXEnhancedStereoStrToID = {{"Unspecified", EnhancedStereoType::UNSPECIFIED},
                                                                                       {"None", EnhancedStereoType::NONE},
                                                                                       {"Absolute", EnhancedStereoType::ABSOLUTE},
                                                                                       {"Or", EnhancedStereoType::OR},
                                                                                       {"And", EnhancedStereoType::AND}};

const std::unordered_map<int, std::string> kCDXEnhancedStereoIDToStr = {{(int)EnhancedStereoType::UNSPECIFIED, "Unspecified"},
                                                                        {(int)EnhancedStereoType::NONE, "None"},
                                                                        {(int)EnhancedStereoType::ABSOLUTE, "Absolute"},
                                                                        {(int)EnhancedStereoType::OR, "Or"},
                                                                        {(int)EnhancedStereoType::AND, "And"}};

const std::unordered_map<uint16_t, std::pair<std::string, ECDXType>> KCDXPropToName = {
    {kCDXProp_CreationUserName, {"CreationUserName", ECDXType::CDXString}},
    {kCDXProp_CreationDate, {"CreationDate", ECDXType::CDXDate}},
    {kCDXProp_CreationProgram, {"CreationProgram", ECDXType::CDXString}},
    {kCDXProp_ModificationUserName, {"ModificationUserName", ECDXType::CDXString}},
    {kCDXProp_ModificationDate, {"ModificationDate", ECDXType::CDXDate}},
    {kCDXProp_ModificationProgram, {"ModificationProgram", ECDXType::CDXString}},
    {kCDXProp_Name, {"Name", ECDXType::CDXString}},
    {kCDXProp_Comment, {"Comment", ECDXType::CDXString}},
    {kCDXProp_ZOrder, {"Z", ECDXType::CDXINT16}},
    {kCDXProp_RegistryNumber, {"RegistryNumber", ECDXType::CDXString}},
    {kCDXProp_RegistryAuthority, {"RegistryAuthority", ECDXType::CDXString}},
    {kCDXProp_RepresentsProperty, {"RepresentsProperty", ECDXType::CDXRepresentsProperty}},
    {kCDXProp_IgnoreWarnings, {"IgnoreWarnings", ECDXType::CDXBooleanImplied}},
    {kCDXProp_ChemicalWarning, {"Warning", ECDXType::CDXString}},
    {kCDXProp_Visible, {"Visible", ECDXType::CDXBoolean}},
    {kCDXProp_SupersededBy, {"SupersededBy", ECDXType::CDXObjectID}},
    {kCDXProp_FontTable, {"fonttable", ECDXType::CDXFontTable}},
    {kCDXProp_2DPosition, {"p", ECDXType::CDXPoint2D}},
    {kCDXProp_3DPosition, {"xyz", ECDXType::CDXPoint3D}},
    {kCDXProp_2DExtent, {"extent", ECDXType::CDXPoint2D}},
    {kCDXProp_3DExtent, {"extent3D", ECDXType::CDXPoint3D}},
    {kCDXProp_BoundingBox, {"BoundingBox", ECDXType::CDXRectangle}},
    {kCDXProp_RotationAngle, {"RotationAngle", ECDXType::CDXINT32}},
    {kCDXProp_3DHead, {"Head3D", ECDXType::CDXPoint3D}},
    {kCDXProp_3DTail, {"Tail3D", ECDXType::CDXPoint3D}},
    {kCDXProp_TopLeft, {"TopLeft", ECDXType::CDXPoint2D}},
    {kCDXProp_TopRight, {"TopRight", ECDXType::CDXPoint2D}},
    {kCDXProp_BottomRight, {"BottomRight", ECDXType::CDXPoint2D}},
    {kCDXProp_BottomLeft, {"BottomLeft", ECDXType::CDXPoint2D}},
    {kCDXProp_3DCenter, {"Center3D", ECDXType::CDXPoint3D}},
    {kCDXProp_3DMajorAxisEnd, {"Center3D", ECDXType::CDXPoint3D}},
    {kCDXProp_3DMinorAxisEnd, {"Center3D", ECDXType::CDXPoint3D}},
    {kCDXProp_ColorTable, {"colortable", ECDXType::CDXColorTable}},
    {kCDXProp_ForegroundColor, {"color", ECDXType::CDXUINT16}},
    {kCDXProp_BackgroundColor, {"bgcolor", ECDXType::CDXColorTableCDXINT16}},
    {kCDXProp_Node_Type, {"NodeType", ECDXType::CDXINT16}},
    {kCDXProp_Node_LabelDisplay, {"LabelDisplay", ECDXType::CDXINT8}},
    {kCDXProp_Node_Element, {"Element", ECDXType::CDXINT16}},
    {kCDXProp_Atom_ElementList, {"ElementList", ECDXType::CDXElementList}},
    {kCDXProp_Atom_Formula, {"Formula", ECDXType::CDXFormula}},
    {kCDXProp_Atom_Isotope, {"Isotope", ECDXType::CDXINT16}},
    {kCDXProp_Atom_Charge, {"Charge", ECDXType::CDXINT8}},
    {kCDXProp_Atom_Radical, {"Radical", ECDXType::CDXUINT8}},
    {kCDXProp_Atom_RestrictFreeSites, {"FreeSites", ECDXType::CDXUINT8}},
    {kCDXProp_Atom_RestrictImplicitHydrogens, {"ImplicitHydrogens", ECDXType::CDXBooleanImplied}},
    {kCDXProp_Atom_RestrictRingBondCount, {"RingBondCount", ECDXType::CDXINT8}},
    {kCDXProp_Atom_RestrictUnsaturatedBonds, {"UnsaturatedBonds", ECDXType::CDXINT8}},
    {kCDXProp_Atom_RestrictRxnChange, {"RxnChange", ECDXType::CDXBooleanImplied}},
    {kCDXProp_Atom_RestrictRxnStereo, {"RxnStereo", ECDXType::CDXINT8}},
    {kCDXProp_Atom_AbnormalValence, {"AbnormalValence", ECDXType::CDXBooleanImplied}},
    {kCDXProp_Atom_NumHydrogens, {"NumHydrogens", ECDXType::CDXUINT16}},
    {kCDXProp_Atom_HDot, {"HDot", ECDXType::CDXBooleanImplied}},
    {kCDXProp_Atom_HDash, {"HDash", ECDXType::CDXBooleanImplied}},
    {kCDXProp_Atom_Geometry, {"Geometry", ECDXType::CDXINT8}},
    {kCDXProp_Atom_BondOrdering, {"BondOrdering", ECDXType::CDXObjectIDArray}},
    {kCDXProp_Node_Attachments, {"Attachments", ECDXType::CDXObjectIDArrayWithCounts}},
    {kCDXProp_Atom_GenericNickname, {"GenericNickname", ECDXType::CDXString}},
    {kCDXProp_Atom_AltGroupID, {"AltGroupID", ECDXType::CDXObjectID}},
    {kCDXProp_Atom_RestrictSubstituentsUpTo, {"SubstituentsUpTo", ECDXType::CDXUINT8}},
    {kCDXProp_Atom_RestrictSubstituentsExactly, {"SubstituentsExactly", ECDXType::CDXUINT8}},
    {kCDXProp_Atom_CIPStereochemistry, {"AS", ECDXType::CDXINT8}},
    {kCDXProp_Atom_Translation, {"Translation", ECDXType::CDXINT8}},
    {kCDXProp_Atom_AtomNumber, {"AtomNumber", ECDXType::CDXString}},
    {kCDXProp_Atom_ShowQuery, {"ShowAtomQuery", ECDXType::CDXBoolean}},
    {kCDXProp_Atom_ShowStereo, {"ShowAtomStereo", ECDXType::CDXBoolean}},
    {kCDXProp_Atom_ShowAtomNumber, {"ShowAtomNumber", ECDXType::CDXBoolean}},
    {kCDXProp_Atom_LinkCountLow, {"LinkCountLow", ECDXType::CDXINT16}},
    {kCDXProp_Atom_LinkCountHigh, {"LinkCountHigh", ECDXType::CDXINT16}},
    {kCDXProp_Atom_IsotopicAbundance, {"IsotopicAbundance", ECDXType::CDXINT8}},
    {kCDXProp_Atom_ExternalConnectionType, {"ExternalConnectionType", ECDXType::CDXINT8}},
    {kCDXProp_Atom_GenericList, {"GenericList", ECDXType::CDXGenericList}},
    {kCDXProp_Atom_ShowTerminalCarbonLabels, {"ShowTerminalCarbonLabels", ECDXType::CDXBooleanImplied}},
    {kCDXProp_Atom_ShowNonTerminalCarbonLabels, {"ShowNonTerminalCarbonLabels", ECDXType::CDXBooleanImplied}},
    {kCDXProp_Atom_HideImplicitHydrogens, {"HideImplicitHydrogens", ECDXType::CDXBooleanImplied}},
    {kCDXProp_Atom_ShowEnhancedStereo, {"ShowAtomEnhancedStereo", ECDXType::CDXBoolean}},
    {kCDXProp_Atom_EnhancedStereoType, {"EnhancedStereoType", ECDXType::CDXUINT8}},
    {kCDXProp_Atom_EnhancedStereoGroupNum, {"EnhancedStereoGroupNum", ECDXType::CDXUINT16}},
    {kCDXProp_Mole_Racemic, {"Racemic", ECDXType::CDXBoolean}},
    {kCDXProp_Mole_Absolute, {"Absolute", ECDXType::CDXBoolean}},
    {kCDXProp_Mole_Relative, {"Relative", ECDXType::CDXBoolean}},
    {kCDXProp_Mole_Formula, {"Formula", ECDXType::CDXFormula}},
    {kCDXProp_Mole_Weight, {"Weight", ECDXType::CDXFLOAT64}},
    {kCDXProp_Frag_ConnectionOrder, {"ConnectionOrder", ECDXType::CDXObjectIDArray}},
    {kCDXProp_Bond_Order, {"Order", ECDXType::CDXINT16}},
    {kCDXProp_Bond_Display, {"Display", ECDXType::CDXINT16}},
    {kCDXProp_Bond_Display2, {"Display2", ECDXType::CDXINT16}},
    {kCDXProp_Bond_DoublePosition, {"DoublePosition", ECDXType::CDXINT16}},
    {kCDXProp_Bond_Begin, {"B", ECDXType::CDXObjectID}},
    {kCDXProp_Bond_End, {"E", ECDXType::CDXObjectID}},
    {kCDXProp_Bond_RestrictTopology, {"Topology", ECDXType::CDXINT8}},
    {kCDXProp_Bond_RestrictRxnParticipation, {"RxnParticipation", ECDXType::CDXINT8}},
    {kCDXProp_Bond_BeginAttach, {"BeginAttach", ECDXType::CDXUINT8}},
    {kCDXProp_Bond_EndAttach, {"EndAttach", ECDXType::CDXUINT8}},
    {kCDXProp_Bond_CIPStereochemistry, {"BS", ECDXType::CDXINT8}},
    {kCDXProp_Bond_BondOrdering, {"BondCircularOrdering", ECDXType::CDXObjectIDArray}},
    {kCDXProp_Bond_ShowQuery, {"ShowBondQuery", ECDXType::CDXBoolean}},
    {kCDXProp_Bond_ShowStereo, {"ShowBondStereo", ECDXType::CDXBoolean}},
    {kCDXProp_Bond_CrossingBonds, {"CrossingBonds", ECDXType::CDXObjectIDArray}},
    {kCDXProp_Bond_ShowRxn, {"ShowBondRxn", ECDXType::CDXBoolean}},
    {kCDXProp_Text, {"t", ECDXType::CDXString}},
    {kCDXProp_Justification, {"Justification", ECDXType::CDXINT8}},
    {kCDXProp_LineHeight, {"LineHeight", ECDXType::CDXUINT16}},
    {kCDXProp_WordWrapWidth, {"WordWrapWidth", ECDXType::CDXINT16}},
    {kCDXProp_LineStarts, {"LineStarts", ECDXType::CDXINT16ListWithCounts}},
    {kCDXProp_LabelAlignment, {"LabelAlignment", ECDXType::CDXINT8}},
    {kCDXProp_LabelLineHeight, {"LabelLineHeight", ECDXType::CDXINT16}},
    {kCDXProp_CaptionLineHeight, {"CaptionLineHeight", ECDXType::CDXINT16}},
    {kCDXProp_InterpretChemically, {"InterpretChemically", ECDXType::CDXBooleanImplied}},
    {kCDXProp_MacPrintInfo, {"MacPrintInfo", ECDXType::CDXUnformatted}},
    {kCDXProp_WinPrintInfo, {"WinPrintInfo", ECDXType::CDXUnformatted}},
    {kCDXProp_PrintMargins, {"PrintMargins", ECDXType::CDXRectangle}},
    {kCDXProp_ChainAngle, {"ChainAngle", ECDXType::CDXINT32}},
    {kCDXProp_BondSpacing, {"BondSpacing", ECDXType::CDXINT16}},
    {kCDXProp_BondLength, {"BondLength", ECDXType::CDXCoordinate}},
    {kCDXProp_BoldWidth, {"BoldWidth", ECDXType::CDXCoordinate}},
    {kCDXProp_LineWidth, {"LineWidth", ECDXType::CDXCoordinate}},
    {kCDXProp_MarginWidth, {"MarginWidth", ECDXType::CDXCoordinate}},
    {kCDXProp_HashSpacing, {"HashSpacing", ECDXType::CDXCoordinate}},
    {kCDXProp_CaptionJustification, {"CaptionJustification", ECDXType::CDXINT8}},
    {kCDXProp_FractionalWidths, {"FractionalWidths", ECDXType::CDXBooleanImplied}},
    {kCDXProp_Magnification, {"Magnification", ECDXType::CDXINT16}},
    {kCDXProp_WidthPages, {"WidthPages", ECDXType::CDXINT16}},
    {kCDXProp_HeightPages, {"HeightPages", ECDXType::CDXINT16}},
    {kCDXProp_DrawingSpaceType, {"DrawingSpace", ECDXType::CDXINT8}},
    {kCDXProp_Width, {"Width", ECDXType::CDXCoordinate}},
    {kCDXProp_Height, {"Height", ECDXType::CDXCoordinate}},
    {kCDXProp_PageOverlap, {"PageOverlap", ECDXType::CDXCoordinate}},
    {kCDXProp_Header, {"Header", ECDXType::CDXString}},
    {kCDXProp_HeaderPosition, {"HeaderPosition", ECDXType::CDXCoordinate}},
    {kCDXProp_Footer, {"Footer", ECDXType::CDXString}},
    {kCDXProp_FooterPosition, {"FooterPosition", ECDXType::CDXCoordinate}},
    {kCDXProp_PrintTrimMarks, {"PrintTrimMarks", ECDXType::CDXBooleanImplied}},
    {kCDXProp_LabelStyleFont, {"LabelFont", ECDXType::CDXINT16}},
    {kCDXProp_CaptionStyleFont, {"CaptionFont", ECDXType::CDXINT16}},
    {kCDXProp_LabelStyleSize, {"LabelSize", ECDXType::CDXINT16}},
    {kCDXProp_CaptionStyleSize, {"CaptionSize", ECDXType::CDXINT16}},
    {kCDXProp_LabelStyleFace, {"LabelFace", ECDXType::CDXINT16}},
    {kCDXProp_CaptionStyleFace, {"CaptionFace", ECDXType::CDXINT16}},
    {kCDXProp_LabelStyleColor, {"LabelColor", ECDXType::CDXINT16}},
    {kCDXProp_CaptionStyleColor, {"CaptionColor", ECDXType::CDXINT16}},
    {kCDXProp_BondSpacingAbs, {"BondSpacingAbs", ECDXType::CDXCoordinate}},
    {kCDXProp_LabelJustification, {"LabelJustification", ECDXType::CDXINT8}},
    {kCDXProp_FixInplaceExtent, {"FixInPlaceExtent", ECDXType::CDXPoint2D}},
    {kCDXProp_Side, {"Side", ECDXType::CDXUINT16}},
    {kCDXProp_FixInplaceGap, {"FixInPlaceGap", ECDXType::CDXPoint2D}},
    {kCDXProp_CartridgeData, {"CartridgeData", ECDXType::CDXUnformatted}},
    {kCDXProp_Window_IsZoomed, {"WindowIsZoomed", ECDXType::CDXBooleanImplied}},
    {kCDXProp_Window_Position, {"WindowPosition", ECDXType::CDXPoint2D}},
    {kCDXProp_Window_Size, {"WindowSize", ECDXType::CDXPoint2D}},
    {kCDXProp_Graphic_Type, {"GraphicType", ECDXType::CDXINT16}},
    {kCDXProp_Line_Type, {"LineType", ECDXType::CDXINT16}},
    {kCDXProp_Arrow_Type, {"ArrowType", ECDXType::CDXINT16}},
    {kCDXProp_Rectangle_Type, {"RectangleType", ECDXType::CDXINT16}},
    {kCDXProp_Oval_Type, {"OvalType", ECDXType::CDXINT16}},
    {kCDXProp_Orbital_Type, {"OrbitalType", ECDXType::CDXINT16}},
    {kCDXProp_Bracket_Type, {"BracketType", ECDXType::CDXINT16}},
    {kCDXProp_Symbol_Type, {"SymbolType", ECDXType::CDXINT16}},
    {kCDXProp_Curve_Type, {"CurveType", ECDXType::CDXINT16}},
    {kCDXProp_Arrow_HeadSize, {"HeadSize", ECDXType::CDXINT16}},
    {kCDXProp_Arc_AngularSize, {"AngularSize", ECDXType::CDXINT16}},
    {kCDXProp_Bracket_LipSize, {"LipSize", ECDXType::CDXINT16}},
    {kCDXProp_Curve_Points, {"CurvePoints", ECDXType::CDXCurvePoints}},
    {kCDXProp_Bracket_Usage, {"BracketUsage", ECDXType::CDXINT8}},
    {kCDXProp_Polymer_RepeatPattern, {"PolymerRepeatPattern", ECDXType::CDXINT8}},
    {kCDXProp_Polymer_FlipType, {"PolymerFlipType", ECDXType::CDXINT8}},
    {kCDXProp_BracketedObjects, {"BracketedObjectIDs", ECDXType::CDXObjectIDArray}},
    {kCDXProp_Bracket_RepeatCount, {"RepeatCount", ECDXType::CDXFLOAT64}},
    {kCDXProp_Bracket_ComponentOrder, {"ComponentOrder", ECDXType::CDXINT16}},
    {kCDXProp_Bracket_SRULabel, {"SRULabel", ECDXType::CDXString}},
    {kCDXProp_Bracket_GraphicID, {"GraphicID", ECDXType::CDXObjectID}},
    {kCDXProp_Bracket_BondID, {"BondID", ECDXType::CDXObjectID}},
    {kCDXProp_Bracket_InnerAtomID, {"InnerAtomID", ECDXType::CDXObjectID}},
    {kCDXProp_Curve_Points3D, {"CurvePoints3D", ECDXType::CDXCurvePoints3D}},
    {kCDXProp_Arrowhead_Type, {"ArrowHeadType", ECDXType::CDXINT16}},
    {kCDXProp_Arrowhead_CenterSize, {"HeadCenterSize", ECDXType::CDXUINT16}},
    {kCDXProp_Arrowhead_Width, {"HeadWidth", ECDXType::CDXUINT16}},
    {kCDXProp_ShadowSize, {"ShadowSize", ECDXType::CDXUINT16}},
    {kCDXProp_Arrow_ShaftSpacing, {"ArrowShaftSpacing", ECDXType::CDXUINT16}},
    {kCDXProp_Arrow_EquilibriumRatio, {"ArrowEquilibriumRatio", ECDXType::CDXUINT16}},
    {kCDXProp_Arrow_ArrowHead_Head, {"ArrowHeadHead", ECDXType::CDXINT16}},
    {kCDXProp_Arrow_ArrowHead_Tail, {"ArrowHeadTail", ECDXType::CDXINT16}},
    {kCDXProp_Fill_Type, {"FillType", ECDXType::CDXINT16}},
    {kCDXProp_Curve_Spacing, {"CurveSpacing", ECDXType::CDXUINT16}},
    {kCDXProp_Closed, {"Closed", ECDXType::CDXBoolean}},
    {kCDXProp_Arrow_Dipole, {"Dipole", ECDXType::CDXBoolean}},
    {kCDXProp_Arrow_NoGo, {"NoGo", ECDXType::CDXINT8}},
    {kCDXProp_CornerRadius, {"CornerRadius", ECDXType::CDXINT16}},
    {kCDXProp_Frame_Type, {"FrameType", ECDXType::CDXINT16}},
    {kCDXProp_Picture_Edition, {"Edition", ECDXType::CDXUnformatted}},
    {kCDXProp_Picture_EditionAlias, {"EditionAlias", ECDXType::CDXUnformatted}},
    {kCDXProp_MacPICT, {"MacPICT", ECDXType::CDXUnformatted}},
    {kCDXProp_WindowsMetafile, {"WindowsMetafile", ECDXType::CDXUnformatted}},
    {kCDXProp_OLEObject, {"OLEObject", ECDXType::CDXUnformatted}},
    {kCDXProp_EnhancedMetafile, {"EnhancedMetafile", ECDXType::CDXUnformatted}},
    {kCDXProp_GIF, {"GIF", ECDXType::CDXUnformatted}},
    {kCDXProp_TIFF, {"TIFF", ECDXType::CDXUnformatted}},
    {kCDXProp_PNG, {"PNG", ECDXType::CDXUnformatted}},
    {kCDXProp_JPEG, {"JPEG", ECDXType::CDXUnformatted}},
    {kCDXProp_BMP, {"BMP", ECDXType::CDXUnformatted}},
    {kCDXProp_Spectrum_XSpacing, {"XSpacing", ECDXType::CDXFLOAT64}},
    {kCDXProp_Spectrum_XLow, {"XLow", ECDXType::CDXFLOAT64}},
    {kCDXProp_Spectrum_XType, {"XType", ECDXType::CDXINT16}},
    {kCDXProp_Spectrum_YType, {"YType", ECDXType::CDXINT16}},
    {kCDXProp_Spectrum_XAxisLabel, {"XAxisLabel", ECDXType::CDXString}},
    {kCDXProp_Spectrum_YAxisLabel, {"YAxisLabel", ECDXType::CDXString}},
    {kCDXProp_Spectrum_Class, {"Class", ECDXType::CDXINT16}},
    {kCDXProp_Spectrum_YLow, {"YLow", ECDXType::CDXFLOAT64}},
    {kCDXProp_Spectrum_YScale, {"YScale", ECDXType::CDXFLOAT64}},
    {kCDXProp_TLC_OriginFraction, {"OriginFraction", ECDXType::CDXFLOAT64}},
    {kCDXProp_TLC_SolventFrontFraction, {"SolventFrontFraction", ECDXType::CDXFLOAT64}},
    {kCDXProp_TLC_ShowOrigin, {"ShowOrigin", ECDXType::CDXBoolean}},
    {kCDXProp_TLC_ShowSolventFront, {"ShowSolventFront", ECDXType::CDXBoolean}},
    {kCDXProp_TLC_ShowBorders, {"ShowBorders", ECDXType::CDXBoolean}},
    {kCDXProp_TLC_ShowSideTicks, {"ShowSideTicks", ECDXType::CDXBoolean}},
    {kCDXProp_TLC_Rf, {"Rf", ECDXType::CDXFLOAT64}},
    {kCDXProp_TLC_Tail, {"Tail", ECDXType::CDXCoordinate}},
    {kCDXProp_TLC_ShowRf, {"ShowRf", ECDXType::CDXBoolean}},
    {kCDXProp_NamedAlternativeGroup_TextFrame, {"TextFrame", ECDXType::CDXRectangle}},
    {kCDXProp_NamedAlternativeGroup_GroupFrame, {"GroupFrame", ECDXType::CDXRectangle}},
    {kCDXProp_NamedAlternativeGroup_Valence, {"Valence", ECDXType::CDXINT16}},
    {kCDXProp_GeometricFeature, {"GeometricFeature", ECDXType::CDXINT8}},
    {kCDXProp_RelationValue, {"RelationValue", ECDXType::CDXFLOAT64}},
    {kCDXProp_BasisObjects, {"BasisObjects", ECDXType::CDXObjectIDArray}},
    {kCDXProp_ConstraintType, {"ConstraintType", ECDXType::CDXINT8}},
    {kCDXProp_ConstraintMin, {"ConstraintMin", ECDXType::CDXFLOAT64}},
    {kCDXProp_ConstraintMax, {"ConstraintMax", ECDXType::CDXFLOAT64}},
    {kCDXProp_IgnoreUnconnectedAtoms, {"IgnoreUnconnectedAtoms", ECDXType::CDXBooleanImplied}},
    {kCDXProp_DihedralIsChiral, {"DihedralIsChiral", ECDXType::CDXBooleanImplied}},
    {kCDXProp_PointIsDirected, {"PointIsDirected", ECDXType::CDXBooleanImplied}},
    {kCDXProp_ChemicalPropertyType, {"ChemicalPropertyType", ECDXType::CDXUINT32}},
    {kCDXProp_ChemicalPropertyDisplayID, {"ChemicalPropertyDisplayID", ECDXType::CDXObjectID}},
    {kCDXProp_ChemicalPropertyIsActive, {"ChemicalPropertyIsActive", ECDXType::CDXBoolean}},
    {kCDXProp_ReactionStep_Atom_Map, {"ReactionStepAtomMap", ECDXType::CDXObjectIDArray}},
    {kCDXProp_ReactionStep_Reactants, {"ReactionStepReactants", ECDXType::CDXObjectIDArray}},
    {kCDXProp_ReactionStep_Products, {"ReactionStepProducts", ECDXType::CDXObjectIDArray}},
    {kCDXProp_ReactionStep_Plusses, {"ReactionStepPlusses", ECDXType::CDXObjectIDArray}},
    {kCDXProp_ReactionStep_Arrows, {"ReactionStepArrows", ECDXType::CDXObjectIDArray}},
    {kCDXProp_ReactionStep_ObjectsAboveArrow, {"ReactionStepObjectsAboveArrow", ECDXType::CDXObjectIDArray}},
    {kCDXProp_ReactionStep_ObjectsBelowArrow, {"ReactionStepObjectsBelowArrow", ECDXType::CDXObjectIDArray}},
    {kCDXProp_ReactionStep_Atom_Map_Manual, {"ReactionStepAtomMapManual", ECDXType::CDXObjectIDArray}},
    {kCDXProp_ReactionStep_Atom_Map_Auto, {"ReactionStepAtomMapAuto", ECDXType::CDXObjectIDArray}},
    {kCDXProp_ObjectTag_Type, {"TagType", ECDXType::CDXINT16}},
    {kCDXProp_ObjectTag_Tracking, {"Tracking", ECDXType::CDXBoolean}},
    {kCDXProp_ObjectTag_Persistent, {"Persistent", ECDXType::CDXBoolean}},
    {kCDXProp_ObjectTag_Value, {"Value", ECDXType::CDXvaries}},
    {kCDXProp_Positioning, {"PositioningType", ECDXType::CDXINT8}},
    {kCDXProp_PositioningAngle, {"PositioningAngle", ECDXType::CDXINT32}},
    {kCDXProp_PositioningOffset, {"PositioningOffset", ECDXType::CDXPoint2D}},
    {kCDXProp_Sequence_Identifier, {"SequenceIdentifier", ECDXType::CDXString}},
    {kCDXProp_CrossReference_Container, {"CrossReferenceContainer", ECDXType::CDXString}},
    {kCDXProp_CrossReference_Document, {"CrossReferenceDocument", ECDXType::CDXString}},
    {kCDXProp_CrossReference_Identifier, {"CrossReferenceIdentifier", ECDXType::CDXString}},
    {kCDXProp_CrossReference_Sequence, {"CrossReferenceSequence", ECDXType::CDXString}},
    {kCDXProp_Template_PaneHeight, {"PaneHeight", ECDXType::CDXCoordinate}},
    {kCDXProp_Template_NumRows, {"NumRows", ECDXType::CDXINT16}},
    {kCDXProp_Template_NumColumns, {"NumColumns", ECDXType::CDXINT16}},
    {kCDXProp_Group_Integral, {"Integral", ECDXType::CDXBoolean}},
    {kCDXProp_SplitterPositions, {"SplitterPositions", ECDXType::CDXObjectIDArray}},
    {kCDXProp_PageDefinition, {"PageDefinition", ECDXType::CDXINT8}}};

const std::unordered_map<uint16_t, std::string> KCDXObjToName = {{kCDXObj_Document, "CDXML"},
                                                                 {kCDXObj_Page, "page"},
                                                                 {kCDXObj_Group, "group"},
                                                                 {kCDXObj_Fragment, "fragment"},
                                                                 {kCDXObj_Node, "n"},
                                                                 {kCDXObj_Bond, "b"},
                                                                 {kCDXObj_Text, "t"},
                                                                 {kCDXObj_Graphic, "graphic"},
                                                                 {kCDXObj_BracketedGroup, "bracketedgroup"},
                                                                 {kCDXObj_BracketAttachment, "bracketattachment"},
                                                                 {kCDXObj_CrossingBond, "crossingbond"},
                                                                 {kCDXObj_Curve, "curve"},
                                                                 {kCDXObj_EmbeddedObject, "embeddedobject"},
                                                                 {kCDXObj_Table, "table"},
                                                                 {kCDXObj_NamedAlternativeGroup, "altgroup"},
                                                                 {kCDXObj_TemplateGrid, "templategrid"},
                                                                 {kCDXObj_RegistryNumber, "regnum"},
                                                                 {kCDXObj_ReactionScheme, "scheme"},
                                                                 {kCDXObj_ReactionStep, "step"},
                                                                 {kCDXObj_Spectrum, "spectrum"},
                                                                 {kCDXObj_ObjectTag, "objecttag"},
                                                                 {kCDXObj_Sequence, "sequence"},
                                                                 {kCDXObj_CrossReference, "crossreference"},
                                                                 {kCDXObj_Border, "border"},
                                                                 {kCDXObj_Geometry, "geometry"},
                                                                 {kCDXObj_Constraint, "constraint"},
                                                                 {kCDXObj_TLCPlate, "tlcplate"},
                                                                 {kCDXObj_TLCLane, "tlclane"},
                                                                 {kCDXObj_TLCSpot, "tlcspot"},
                                                                 {kCDXObj_Splitter, "splitter"},
                                                                 {kCDXObj_ChemicalProperty, "chemicalproperty"},
                                                                 {kCDXProp_ColorTable, "colortable"},
                                                                 {kCDXProp_FontTable, "fonttable"},
                                                                 {kCDXProp_RepresentsProperty, "represent"},
                                                                 {kCDXObj_Arrow, "arrow"}};

const std::unordered_map<std::string, int> KNodeTypeNameToInt = {{"Unspecified", kCDXNodeType_Unspecified},
                                                                 {"Element", kCDXNodeType_Element},
                                                                 {"ElementList", kCDXNodeType_ElementList},
                                                                 {"ElementListNickname", kCDXNodeType_ElementListNickname},
                                                                 {"Nickname", kCDXNodeType_Nickname},
                                                                 {"Fragment", kCDXNodeType_Fragment},
                                                                 {"Formula", kCDXNodeType_Formula},
                                                                 {"GenericNickname", kCDXNodeType_GenericNickname},
                                                                 {"AnonymousAlternativeGroup", kCDXNodeType_AnonymousAlternativeGroup},
                                                                 {"NamedAlternativeGroup", kCDXNodeType_NamedAlternativeGroup},
                                                                 {"MultiAttachment", kCDXNodeType_MultiAttachment},
                                                                 {"VariableAttachment", kCDXNodeType_VariableAttachment},
                                                                 {"ExternalConnectionPoint", kCDXNodeType_ExternalConnectionPoint},
                                                                 {"LinkNode", kCDXNodeType_LinkNode}};

const std::unordered_map<int, std::string> KNodeTypeIntToName = {{kCDXNodeType_Unspecified, "Unspecified"},
                                                                 {kCDXNodeType_Element, "Element"},
                                                                 {kCDXNodeType_ElementList, "ElementList"},
                                                                 {kCDXNodeType_ElementListNickname, "ElementListNickname"},
                                                                 {kCDXNodeType_Nickname, "Nickname"},
                                                                 {kCDXNodeType_Fragment, "Fragment"},
                                                                 {kCDXNodeType_Formula, "Formula"},
                                                                 {kCDXNodeType_GenericNickname, "GenericNickname"},
                                                                 {kCDXNodeType_AnonymousAlternativeGroup, "AnonymousAlternativeGroup"},
                                                                 {kCDXNodeType_NamedAlternativeGroup, "NamedAlternativeGroup"},
                                                                 {kCDXNodeType_MultiAttachment, "MultiAttachment"},
                                                                 {kCDXNodeType_VariableAttachment, "VariableAttachment"},
                                                                 {kCDXNodeType_ExternalConnectionPoint, "ExternalConnectionPoint"},
                                                                 {kCDXNodeType_LinkNode, "LinkNode"}};

const std::unordered_map<std::string, int> KGeometryTypeNameToInt = {{"Unspecified", kCDXAtomGeometry_Unknown},
                                                                     {"1", kCDXAtomGeometry_1Ligand},
                                                                     {"Linear", kCDXAtomGeometry_Linear},
                                                                     {"Bent", kCDXAtomGeometry_Bent},
                                                                     {"TrigonalPlanar", kCDXAtomGeometry_TrigonalPlanar},
                                                                     {"TrigonalPyramidal", kCDXAtomGeometry_TrigonalPyramidal},
                                                                     {"SquarePlanar", kCDXAtomGeometry_SquarePlanar},
                                                                     {"Tetrahedral", kCDXAtomGeometry_Tetrahedral},
                                                                     {"TrigonalBipyramidal", kCDXAtomGeometry_TrigonalBipyramidal},
                                                                     {"SquarePyramidal", kCDXAtomGeometry_SquarePyramidal},
                                                                     {"5", kCDXAtomGeometry_5Ligand},
                                                                     {"Octahedral", kCDXAtomGeometry_Octahedral},
                                                                     {"6", kCDXAtomGeometry_6Ligand},
                                                                     {"7", kCDXAtomGeometry_7Ligand},
                                                                     {"8", kCDXAtomGeometry_8Ligand},
                                                                     {"9", kCDXAtomGeometry_9Ligand},
                                                                     {"10", kCDXAtomGeometry_10Ligand}};

const std::unordered_map<int, std::string> KGeometryTypeIntToName = {{kCDXAtomGeometry_Unknown, "Unspecified"},
                                                                     {kCDXAtomGeometry_1Ligand, "1"},
                                                                     {kCDXAtomGeometry_Linear, "Linear"},
                                                                     {kCDXAtomGeometry_Bent, "Bent"},
                                                                     {kCDXAtomGeometry_TrigonalPlanar, "TrigonalPlanar"},
                                                                     {kCDXAtomGeometry_TrigonalPyramidal, "TrigonalPyramidal"},
                                                                     {kCDXAtomGeometry_SquarePlanar, "SquarePlanar"},
                                                                     {kCDXAtomGeometry_Tetrahedral, "Tetrahedral"},
                                                                     {kCDXAtomGeometry_TrigonalBipyramidal, "TrigonalBipyramidal"},
                                                                     {kCDXAtomGeometry_SquarePyramidal, "SquarePyramidal"},
                                                                     {kCDXAtomGeometry_5Ligand, "5"},
                                                                     {kCDXAtomGeometry_Octahedral, "Octahedral"},
                                                                     {kCDXAtomGeometry_6Ligand, "6"},
                                                                     {kCDXAtomGeometry_7Ligand, "7"},
                                                                     {kCDXAtomGeometry_8Ligand, "8"},
                                                                     {kCDXAtomGeometry_9Ligand, "9"},
                                                                     {kCDXAtomGeometry_10Ligand, "10"}};

const std::unordered_map<std::string, int> kBracketUsageNameToInt = {{"Unspecified", kCDXBracketUsage_Unspecified},
                                                                     {"Unused1", kCDXBracketUsage_Unused1},
                                                                     {"Unused2", kCDXBracketUsage_Unused2},
                                                                     {"SRU", kCDXBracketUsage_SRU},
                                                                     {"Monomer", kCDXBracketUsage_Monomer},
                                                                     {"Mer", kCDXBracketUsage_Mer},
                                                                     {"Copolymer", kCDXBracketUsage_Copolymer},
                                                                     {"CopolymerAlternating", kCDXBracketUsage_CopolymerAlternating},
                                                                     {"CopolymerRandom", kCDXBracketUsage_CopolymerRandom},
                                                                     {"CopolymerBlock", kCDXBracketUsage_CopolymerBlock},
                                                                     {"Crosslink", kCDXBracketUsage_Crosslink},
                                                                     {"Graft", kCDXBracketUsage_Graft},
                                                                     {"Modification", kCDXBracketUsage_Modification},
                                                                     {"Component", kCDXBracketUsage_Component},
                                                                     {"MixtureUnordered", kCDXBracketUsage_MixtureUnordered},
                                                                     {"MixtureOrdered", kCDXBracketUsage_MixtureOrdered},
                                                                     {"MultipleGroup", kCDXBracketUsage_MultipleGroup},
                                                                     {"Generic", kCDXBracketUsage_Generic},
                                                                     {"Anypolymer", kCDXBracketUsage_Anypolymer}

};

const std::unordered_map<int, std::string> kBracketUsageIntToName = {{kCDXBracketUsage_Unspecified, "Unspecified"},
                                                                     {kCDXBracketUsage_Unused1, "Unused1"},
                                                                     {kCDXBracketUsage_Unused2, "Unused2"},
                                                                     {kCDXBracketUsage_SRU, "SRU"},
                                                                     {kCDXBracketUsage_Monomer, "Monomer"},
                                                                     {kCDXBracketUsage_Mer, "Mer"},
                                                                     {kCDXBracketUsage_Copolymer, "Copolymer"},
                                                                     {kCDXBracketUsage_CopolymerAlternating, "CopolymerAlternating"},
                                                                     {kCDXBracketUsage_CopolymerRandom, "CopolymerRandom"},
                                                                     {kCDXBracketUsage_CopolymerBlock, "CopolymerBlock"},
                                                                     {kCDXBracketUsage_Crosslink, "Crosslink"},
                                                                     {kCDXBracketUsage_Graft, "Graft"},
                                                                     {kCDXBracketUsage_Modification, "Modification"},
                                                                     {kCDXBracketUsage_Component, "Component"},
                                                                     {kCDXBracketUsage_MixtureUnordered, "MixtureUnordered"},
                                                                     {kCDXBracketUsage_MixtureOrdered, "MixtureOrdered"},
                                                                     {kCDXBracketUsage_MultipleGroup, "MultipleGroup"},
                                                                     {kCDXBracketUsage_Generic, "Generic"},
                                                                     {kCDXBracketUsage_Anypolymer, "Anypolymer"}};

const std::vector<char> KCIPStereochemistryIndexToChar = {'U', 'N', 'R', 'S', 'r', 's', 'u'};
const std::unordered_map<char, uint8_t> KCIPStereochemistryCharToIndex = {{'U', 0}, {'N', 1}, {'R', 2}, {'S', 3}, {'r', 4}, {'s', 5}, {'u', 6}};
const std::vector<std::string> KStyleProperties = {"font", "face", "size", "color"};

#endif // _H_CDXCommons
