version: "3.4"

services:
  db:
    build:
      context: ./db/
      dockerfile: ./Dockerfile
    env_file: ./env/db.env
    ports:
      - "5432:5432"
    restart: always

  elastic:
    image: elasticsearch:8.8.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false

  backend-postgres:
    build:
      context: ./backend/service/postgres
      dockerfile: ./Dockerfile
    env_file: ./env/db.env
    depends_on:
      - db
    restart: always
    command: supervisord -n

  backend-elastic:
    build:
      context: ./backend/service/elastic
      dockerfile: ./Dockerfile
    depends_on:
      - elastic
    restart: always
    command: supervisord -n

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    env_file: ./frontend/ui/.env
    depends_on:
      - backend-postgres
    ports:
      - "8080:80"
    restart: always

