version: "3.4"

services:
  db:
    build:
      context: ./db/
      dockerfile: ./Dockerfile
    env_file: ./env/db.env
    ports:
      - "5432:5432"
    volumes:
      - db_pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    env_file: ./env/db.env
    depends_on:
      - db
    restart: always
    command: supervisord -n

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always

volumes:
  db_pgdata:
