[tool.black]
line_length = 79

[tool.flake8]
max-line-length = 79
extend-ignore = "E203, E501, F405"
exclude = "api/tests/integration"

[tool.isort]
profile = "black"
line_length = 79

[tool.mypy]
ignore_missing_imports = true

[tool.pylint.MASTER]
disable= [
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
    "too-few-public-methods",
    "unsubscriptable-object",
    "duplicate-code"
]
