import sys
sys.path.append('../../common')
from env_indigo import *

indigo = Indigo()
indigo.setOption("fp-sim-qwords", 1)
indigo.setOption("fp-ord-qwords", 0)
indigo.setOption("fp-tau-qwords", 0)
indigo.setOption("fp-any-qwords", 0)
mol = indigo.loadMolecule("[Cl]c1ccccc1(N)OC(=P)C(CC)C1CCC1")
fp = mol.fingerprint("sim")
print(len(fp.toBuffer()))
print(fp.toString())
indigo.setOption("fp-ext-enabled", False)
fp = mol.fingerprint("sim")
print(len(fp.toBuffer()))
print(fp.toString())
indigo.setOption("fp-sim-qwords", 8)
fp = mol.fingerprint("sim")
print(len(fp.toBuffer()))
print(fp.toString())
indigo.setOption("fp-ext-enabled", True)
fp = mol.fingerprint("sim")
print(len(fp.toBuffer()))
print(fp.toString())
