static const char* regexes_table = 
  "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
  "<tokenTables>\n"
  "  <tokenTable name=\"regexes\" type=\"acids\">\n"
  "    <token smiles=\"(=O)O\">oic acid</token>\n"
  "    <token smiles=\"C(=O)O\">carboxylic acid</token>\n"
  "    <token smiles=\"S(=O)(=O)O\">sulphonic acid</token>\n"
  "    <token smiles=\"S(=O)O\">sulphinic acid</token>\n"
  "    <token smiles=\"[Se](=O)(=O)O\">selenonic acid</token>\n"
  "    <token smiles=\"[Se](=O)O\">seleninic acid</token>\n"
  "    <token smiles=\"[Te](=O)(=O)O\">telluronic acid</token>\n"
  "    <token smiles=\"[Te](=O)O\">tellurinic acid</token>\n"
  "  </tokenTable>\n"
  "</tokenTables>\n";
