IF(MSVC)
	set(SYSTEM_FOLDER_NAME "Win")
	IF(CMAKE_SIZEOF_VOID_P MATCHES 8)
		set(SUBSYSTEM_FOLDER_NAME "x64")
	ELSE()
		set(SUBSYSTEM_FOLDER_NAME "x86")
	ENDIF()
ELSEIF(APPLE)
	set(SYSTEM_FOLDER_NAME "Mac")
	# http://www.cmake.org/pipermail/cmake/2007-October/017286.html
   MESSAGE(FATAL_ERROR "Not implemented yet. Need to parse files.")
ELSEIF(UNIX)
	set(SYSTEM_FOLDER_NAME "Linux")
	IF(CMAKE_SIZEOF_VOID_P MATCHES 8)
		set(SUBSYSTEM_FOLDER_NAME "x64")
	ELSE()
		set(SUBSYSTEM_FOLDER_NAME "x86")
	ENDIF()
ELSE()
   MESSAGE(FATAL_ERROR "Unsupported system")
ENDIF()

MESSAGE(STATUS "System-specific folder name: ${SYSTEM_FOLDER_NAME}")
MESSAGE(STATUS "Subsystem-specific folder name: ${SUBSYSTEM_FOLDER_NAME}")
