# http://stackoverflow.com/questions/822404/how-to-set-up-cmake-to-build-an-app-for-the-iphone

macro(ADD_FRAMEWORK fwname appname)
	set(FRAMEWORK_${fwname} /Developer/SDKs/MacOSX${SUBSYSTEM_NAME}.sdk/System/Library/Frameworks/${fwname}.framework)
    if(NOT IS_DIRECTORY ${FRAMEWORK_${fwname}})
        MESSAGE(ERROR ": Framework ${fwname} not found")
    else()
        TARGET_LINK_LIBRARIES(${appname} ${FRAMEWORK_${fwname}})
        MESSAGE(STATUS "Framework ${fwname} found at ${FRAMEWORK_${fwname}}")
    endif()
endmacro()

macro(FIND_FRAMEWORK fwname)
	set(FRAMEWORK_${fwname} /Developer/SDKs/MacOSX${SUBSYSTEM_NAME}.sdk/System/Library/Frameworks/${fwname}.framework)	
    if(NOT IS_DIRECTORY ${FRAMEWORK_${fwname}})
        MESSAGE(ERROR ": Framework ${fwname} not found")
    else()
        MESSAGE(STATUS "Framework ${fwname} found at ${FRAMEWORK_${fwname}}")
    endif()
endmacro()