set(COMMON_OUTPUT_PATH dist/${SYSTEM_NAME}/${SUBSYSTEM_NAME})
set(LIBRARY_OUTPUT_PATH ${CMAKE_BINARY_DIR}/${COMMON_OUTPUT_PATH}/lib)
set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/${COMMON_OUTPUT_PATH}/bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${COMMON_OUTPUT_PATH}/shared)

MESSAGE(STATUS "Common output dir: ${CMAKE_BINARY_DIR}/${COMMON_OUTPUT_PATH}")

macro(PACK_STATIC proj)
	INSTALL(TARGETS ${proj}
		DESTINATION static/${SYSTEM_NAME}/${SUBSYSTEM_NAME}
		COMPONENT static)
endmacro()

macro(PACK_SHARED proj)
	INSTALL(TARGETS ${proj}
		DESTINATION shared/${SYSTEM_NAME}/${SUBSYSTEM_NAME}
		COMPONENT shared)
endmacro()
