if(NOT MSVC)
	set(VISIBILITY_HIDDEN YES)
endif()
if(NOT BUILD_DEBUG)
    set(CMAKE_BUILD_TYPE Release)
else()
    set(CMAKE_BUILD_TYPE Debug)
endif()
if(UNIX)
	if (SUBSYSTEM_NAME MATCHES "x86")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m32")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m32")	
	elseif(SUBSYSTEM_NAME MATCHES "x64")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m64")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m64")
	endif()
endif()
if(APPLE)
    set(CMAKE_OSX_ARCHITECTURES "i386;x86_64")
endif()
if(VISIBILITY_HIDDEN)
    SET(COMPILE_FLAGS "${COMPILE_FLAGS} -fvisibility=hidden")
endif()   
if(UNIX OR APPLE)
    SET(COMPILE_FLAGS "${COMPILE_FLAGS} -fPIC")
endif() 
