SET(BINGO_VERSION "1.7.6")

IF(BUILD_VERSION)
   SET(BINGO_BUILD_VERSION ${BUILD_VERSION})
ELSE()
   SET(BINGO_BUILD_VERSION 0)
ENDIF()

SET(BINGO_VERSION_EXT "${BINGO_VERSION}.${BINGO_BUILD_VERSION} ${PACKAGE_SUFFIX}")
