//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace indigo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("  ", typeof(resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER {0}
        ///	ON {1}
        ///	FOR DELETE
        ///AS
        ///	-- Create global cursor for deleted records
        ///	-- Simultaneous inserts from different sessions are not supported
        ///	declare [bingotmpcur_del_{5}_{6}] cursor GLOBAL FORWARD_ONLY READ_ONLY for select {2} from deleted
        ///	open [bingotmpcur_del_{5}_{6}]
        ///
        ///	-- Cursor will be deallocated in the _OnInsertRecordTrigger automatically
        ///	exec {4}._OnDeleteRecordTrigger {5}, {6}, &apos;[bingotmpcur_del_{5}_{6}]&apos;
        ///.
        /// </summary>
        internal static string OnDeleteTrigger {
            get {
                return ResourceManager.GetString("OnDeleteTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER {0}
        ///	ON {1}
        ///	FOR INSERT
        ///AS
        ///	-- Create global cursor for inserted records
        ///	-- Simultaneous inserts from different sessions are not supported
        ///	declare [bingotmpcur_{5}_{6}] cursor GLOBAL FORWARD_ONLY READ_ONLY for select {2}, {3} from inserted
        ///	open [bingotmpcur_{5}_{6}]
        ///
        ///	-- Cursor will be deallocated in the _OnInsertRecordTrigger automatically
        ///	exec {4}._OnInsertRecordTrigger {5}, {6}, &apos;[bingotmpcur_{5}_{6}]&apos;
        ///.
        /// </summary>
        internal static string OnInsertTrigger {
            get {
                return ResourceManager.GetString("OnInsertTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER {0}
        ///	ON {1}
        ///	FOR UPDATE
        ///AS
        ///	IF UPDATE({2}) 
        ///	BEGIN 
        ///		RAISERROR (&apos;{2} column cannot be changed after Bingo index has been created.&apos;, 16, 1);
        ///		ROLLBACK TRANSACTION
        ///	END
        ///	
        ///	IF NOT UPDATE({3}) 
        ///	BEGIN 
        ///		RETURN 
        ///	END
        ///	
        ///	-- At first delete records and then insert them
        ///
        ///	-- Create global cursor for deleted records
        ///	-- Simultaneous inserts from different sessions are not supported
        ///	declare [bingotmpcur_upd_{5}_{6}] cursor GLOBAL FORWARD_ONLY READ_ONLY for select {2} from inserte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OnUpdateTrigger {
            get {
                return ResourceManager.GetString("OnUpdateTrigger", resourceCulture);
            }
        }
        
        internal static byte[] Win_x64_bingo_core_c_dll {
            get {
                object obj = ResourceManager.GetObject("bingo-core-c.dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
