//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace indigo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("indigo.resource", typeof(resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bingo_core_c_dll {
            get {
                object obj = ResourceManager.GetObject("bingo-core-c.dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER {0}
        ///	ON {1}
        ///	FOR DELETE
        ///AS
        ///	IF OBJECT_ID(&apos;tempdb..##bingotmptbl_{5}_{6}&apos;) IS NOT NULL
        ///	BEGIN
        ///		DROP TABLE ##bingotmptbl_{5}_{6}
        ///	END
        ///	select {2} into ##bingotmptbl_{5}_{6} from deleted 
        ///
        ///	exec {4}._OnDeleteRecordTrigger {5}, {6}, &apos;##bingotmptbl_{5}_{6}&apos;
        ///	DROP TABLE ##bingotmptbl_{5}_{6}
        ///.
        /// </summary>
        public static string OnDeleteTrigger {
            get {
                return ResourceManager.GetString("OnDeleteTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER {0}
        ///	ON {1}
        ///	FOR INSERT
        ///AS
        ///	IF OBJECT_ID(&apos;tempdb..##bingotmptbl_{5}_{6}&apos;) IS NOT NULL
        ///	BEGIN
        ///		DROP TABLE ##bingotmptbl_{5}_{6}
        ///	END
        ///	select {2}, {3} into ##bingotmptbl_{5}_{6} from inserted 
        ///
        ///	exec {4}._OnInsertRecordTrigger {5}, {6}, &apos;##bingotmptbl_{5}_{6}&apos;
        ///	DROP TABLE ##bingotmptbl_{5}_{6}
        ///.
        /// </summary>
        public static string OnInsertTrigger {
            get {
                return ResourceManager.GetString("OnInsertTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER {0}
        ///	ON {1}
        ///	FOR UPDATE
        ///AS
        ///	IF UPDATE({2}) 
        ///	BEGIN 
        ///		RAISERROR (&apos;{2} column cannot be changed after Bingo index has been created.&apos;, 16, 1);
        ///		ROLLBACK TRANSACTION
        ///	END
        ///	
        ///	IF NOT UPDATE({3}) 
        ///	BEGIN 
        ///		RETURN 
        ///	END
        ///	
        ///	IF OBJECT_ID(&apos;tempdb..##bingotmptbl_{5}_{6}&apos;) IS NOT NULL
        ///	BEGIN
        ///		DROP TABLE ##bingotmptbl_{5}_{6}
        ///	END
        ///	select {2}, {3} into ##bingotmptbl_{5}_{6} from inserted 
        ///
        ///	exec {4}._OnDeleteRecordTrigger {5}, {6}, &apos;##bingotmptbl_{5}_{6}&apos;
        ///	exec {4}._OnInsertRecordT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OnUpdateTrigger {
            get {
                return ResourceManager.GetString("OnUpdateTrigger", resourceCulture);
            }
        }
    }
}
