/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dc_indigo_graph_impl_GraphItemGeneratedImpl */

#ifndef _Included_com_dc_indigo_graph_impl_GraphItemGeneratedImpl
#define _Included_com_dc_indigo_graph_impl_GraphItemGeneratedImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dc_indigo_graph_impl_GraphItemGeneratedImpl
 * Method:    _getHighlighted
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dc_indigo_graph_impl_GraphItemGeneratedImpl__1getHighlighted
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dc_indigo_graph_impl_GraphItemGeneratedImpl
 * Method:    _setLabel
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dc_indigo_graph_impl_GraphItemGeneratedImpl__1setLabel
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_dc_indigo_graph_impl_GraphItemGeneratedImpl
 * Method:    _getSelected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dc_indigo_graph_impl_GraphItemGeneratedImpl__1getSelected
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dc_indigo_graph_impl_GraphItemGeneratedImpl
 * Method:    _getStyle
 * Signature: (I)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_dc_indigo_graph_impl_GraphItemGeneratedImpl__1getStyle
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dc_indigo_graph_impl_GraphItemGeneratedImpl
 * Method:    _getLabel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dc_indigo_graph_impl_GraphItemGeneratedImpl__1getLabel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dc_indigo_graph_impl_GraphItemGeneratedImpl
 * Method:    _getCoord3d
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dc_indigo_graph_impl_GraphItemGeneratedImpl__1getCoord3d
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dc_indigo_graph_impl_GraphItemGeneratedImpl
 * Method:    _setSelected
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_dc_indigo_graph_impl_GraphItemGeneratedImpl__1setSelected
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_dc_indigo_graph_impl_GraphItemGeneratedImpl
 * Method:    _setHighlighted
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_dc_indigo_graph_impl_GraphItemGeneratedImpl__1setHighlighted
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_dc_indigo_graph_impl_GraphItemGeneratedImpl
 * Method:    _getGraph
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dc_indigo_graph_impl_GraphItemGeneratedImpl__1getGraph
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
