package:
    name: indigo
    version: 1.10.0

source:
    git_url: https://github.com/epam/indigo.git
    git_rev: e665348e3472f9f324547d04b1c11e65291fb877

requirements:
    build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python
    - cairo
    - inchi
    - rapidjson
    - tinyxml2
    run:
    - python
    - cairo
    - inchi
    - tinyxml2

about:
    home: https://lifescience.opensource.epam.com/indigo/index.html
    description: "Cheminformatics toolkit"
    license: Apache-2.0
