package:
    name: indigo
    version: 1.10.0

source:
    git_url: https://github.com/epam/indigo.git
    git_rev: 48f6d154f17c460635c20fa815eb691b2c41ef45

requirements:
    build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python
    - cairo
    - tinyxml2
    run:
    - python
    - cairo
    - tinyxml2

about:
    home: https://lifescience.opensource.epam.com/indigo/index.html
    description:
    license: Apache-2.0
