FROM docker.elastic.co/elasticsearch/elasticsearch:6.1.1

COPY elasticsearch.yml /usr/share/elasticsearch/config/

USER elasticsearch
ENV PATH=$PATH:/usr/share/elasticsearch/bin
CMD ["elasticsearch"]

EXPOSE 9200 9300