FROM indigo-lucene/elastic-base

#Ports for elastic
EXPOSE 9200
EXPOSE 9300

RUN chown -R $SOLR_USER:$SOLR_USER $ELASTIC_DIR

COPY ../configs/logging.yml $ELASTIC_DIR/config/
COPY ../configs/elasticsearch.yml $ELASTIC_DIR/config/

RUN echo "$SOLR_USER:solr" | chpasswd && adduser $SOLR_USER sudo && \
    echo "$SOLR_USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN printf "grant codebase \"file:/usr/lib/jvm/java-1.8.0-openjdk-amd64/lib/tools.jar\" {\n permission java.security.AllPermission;\n        };\n" > $JAVA_HOME/bin/jstatd.all.policy
RUN sed -i '/ENABLE_REMOTE_JMX_OPTS/d' /opt/solr/bin/solr.in.sh

ENV ENABLE_REMOTE_JMX_OPTS "true"
ENV RMI_PORT 6901
ENV SOLR_STARTUP_PARAMS "-a \"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6900\""

USER $SOLR_USER
WORKDIR $ELASTIC_DIR

CMD ["/bin/bash", "./elastic-startup.sh"]
