cluster.name: "my-cluster"
node.name: moldocs

http.port: 9200
transport.tcp.port: 9300
network.host: 0.0.0.0
transport.host: 127.0.0.1
discovery.zen.ping.unicast.hosts: ["127.0.0.1"]

xpack.security.enabled: false

#discovery.zen.minimum_master_nodes: 1
#network.bind_host: 0
#node.master: true
#node.data: true