Build:

  Note: you should have the "zip" command-line utility installed on your system.

  On Linux, run

    ./all-release-linux.sh $version

  On Windows, run

    all-release-windows.bat $version

  On Mac OS X, run

    not supported yet

  On Solaris, run:

    not supported yet

  You will get a number of .zip archives for your selected platform,
  both 32-bit and 64-bit versions.
  (In case of Mac OS X, both 10.5 and 10.6 versions.)
