/* DO NOT EDIT THIS FILE - it is machine generated */
package com.dc.indigo.graph.impl;


public class GraphGeneratedImpl extends com.dc.indigo.core.impl.ItemImpl implements com.dc.indigo.graph.Graph {
	
	protected GraphGeneratedImpl(int thisID) {
		super(thisID);
	}
 
}



