/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CellFrame.java
 *
 * Created on Mar 31, 2011, 12:43:58 PM
 */

package com.ggasoftware.indigo.controls;

import com.ggasoftware.indigo.Indigo;
import com.ggasoftware.indigo.IndigoObject;
import com.ggasoftware.indigo.IndigoRenderer;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author achurinov
 */
public class CellFrame extends javax.swing.JFrame {
   private Indigo _indigo;
   private IndigoRenderer _indigo_renderer;
   private IndigoObject _obj;
   private boolean _is_reaction;

   /** Creates new form CellFrame */
   public CellFrame() {
       initComponents();
   }

   public void init(Indigo indigo, IndigoRenderer indigo_renderer, 
                    RenderableObject rend_obj, boolean is_reaction)
   {
      this._indigo = indigo;
      this._indigo_renderer = indigo_renderer;
      this._obj = rend_obj.getObject();
      this._is_reaction = is_reaction;

      if (!_obj.hasCoord())
         _obj.layout();
      mol_view_panel.init(_indigo, _indigo_renderer);
      mol_view_panel.setMol(_obj);

      String mol_name = _obj.name();

      if (true || mol_name == null || mol_name.length() == 0)
      {
         try {
            mol_name = _obj.canonicalSmiles();
         } catch (Exception ex) {
            mol_name = null;
         }
      }

      _fillPropertyTable();

      mol_view_panel.setSize(mol_view_panel.getPreferredSize());

      setTitle(mol_name);

      // Set window position in the middle
      Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
      Dimension windowSize = getSize();
      int windowX = Math.max(0, (screenSize.width - windowSize.width) / 2);
      int windowY = Math.max(0, (screenSize.height - windowSize.height) / 2);

      setLocation(windowX, windowY);

      setVisible(true);
      setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
   }

   private void _fillPropertyTable()
   {
      DefaultTableModel model = (DefaultTableModel) property_table.getModel();
      while (model.getRowCount() != 0)
         model.removeRow(0);
      
      for (IndigoObject prop : _obj.iterateProperties())
      {
         String prop_name = prop.name();
         String prop_value = _obj.getProperty(prop.name());

         model.addRow(new String[] {prop_name, prop_value});
      }
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      mol_view_panel = new com.ggasoftware.indigo.controls.MolViewPanel();
      property_scroll_panel = new javax.swing.JScrollPane();
      property_table = new javax.swing.JTable();
      menu_bar = new javax.swing.JMenuBar();
      file_menu = new javax.swing.JMenu();
      save_mi = new javax.swing.JMenuItem();
      exit_mi = new javax.swing.JMenuItem();
      edit_menu = new javax.swing.JMenu();
      layout_mi = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      javax.swing.GroupLayout mol_view_panelLayout = new javax.swing.GroupLayout(mol_view_panel);
      mol_view_panel.setLayout(mol_view_panelLayout);
      mol_view_panelLayout.setHorizontalGroup(
         mol_view_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 330, Short.MAX_VALUE)
      );
      mol_view_panelLayout.setVerticalGroup(
         mol_view_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 291, Short.MAX_VALUE)
      );

      property_scroll_panel.setBorder(null);

      property_table.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "Property name", "Value"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class
         };
         boolean[] canEdit = new boolean [] {
            false, false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      property_scroll_panel.setViewportView(property_table);

      file_menu.setText("File");

      save_mi.setText("Save As");
      save_mi.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            save_miActionPerformed(evt);
         }
      });
      file_menu.add(save_mi);

      exit_mi.setText("Exit");
      exit_mi.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            exit_miActionPerformed(evt);
         }
      });
      file_menu.add(exit_mi);

      menu_bar.add(file_menu);

      edit_menu.setText("Edit");

      layout_mi.setText("Layout");
      layout_mi.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            layout_miActionPerformed(evt);
         }
      });
      edit_menu.add(layout_mi);

      menu_bar.add(edit_menu);

      setJMenuBar(menu_bar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(mol_view_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(property_scroll_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(mol_view_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(property_scroll_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void save_miActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_miActionPerformed
       MolSaver mol_saver = new MolSaver(_indigo);
       mol_saver.addExtension("cml");
       if (!_is_reaction)
       {
          mol_saver.addExtension("smi");
          mol_saver.addExtension("mol");
       }
       else
          mol_saver.addExtension("rxn");
       mol_saver.saveMol(new RenderableObject() {
         public IndigoObject getObject() {
            return _obj;
         }
      });
    }//GEN-LAST:event_save_miActionPerformed

    private void exit_miActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_miActionPerformed
       dispose();
    }//GEN-LAST:event_exit_miActionPerformed

    private void layout_miActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layout_miActionPerformed
       _obj.layout();
       mol_view_panel.setMol(_obj);
    }//GEN-LAST:event_layout_miActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenu edit_menu;
   private javax.swing.JMenuItem exit_mi;
   private javax.swing.JMenu file_menu;
   private javax.swing.JMenuItem layout_mi;
   private javax.swing.JMenuBar menu_bar;
   private com.ggasoftware.indigo.controls.MolViewPanel mol_view_panel;
   private javax.swing.JScrollPane property_scroll_panel;
   private javax.swing.JTable property_table;
   private javax.swing.JMenuItem save_mi;
   // End of variables declaration//GEN-END:variables

}
