SET(INDIGO_VERSION "1.1.6")

IF(BUILD_NUMBER)
   SET(INDIGO_BUILD_VERSION ${BUILD_NUMBER})
ELSE()
   SET(INDIGO_BUILD_VERSION 0)
ENDIF()

SET(INDIGO_VERSION_EXT "${INDIGO_VERSION}.${INDIGO_BUILD_VERSION} ${PACKAGE_SUFFIX}")
