SET(INDIGO_VERSION "1.1.10")

IF($ENV{BUILD_NUMBER})
   SET(INDIGO_BUILD_VERSION $ENV{BUILD_NUMBER})
ELSE()
   SET(INDIGO_BUILD_VERSION 0)
ENDIF()

SET(INDIGO_VERSION_EXT "${INDIGO_VERSION}.${INDIGO_BUILD_VERSION} ${PACKAGE_SUFFIX}")
