name: gitlab_tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger gitlab pipeline
      shell: bash
      env:
        GITLAB_PROJECTS_ID: 7023
        GITLAB_PIPELINE_TOKEN: ${{ secrets.GITLAB_PIPELINE_TOKEN }}
      run: |
        curl -X POST -F token=$GITLAB_PIPELINE_TOKEN  -F ref=master -F "variables[SRC_REV]=$GITHUB_SHA" https://git.epam.com/api/v4/projects/$GITLAB_PROJECTS_ID/trigger/pipeline
